config/routes.rb
Rails.application.routes.draw do

  get 'pages/:slug' => 'pages#show', as: :page
  root 'pages#home', { slug: "home" }

  get 'login' => 'users#show_login', as: :login
  post 'login' => 'users#login'
  get 'logout' => 'users#logout', as: :logout

  scope '/admin' do
    resources :categories, except: [:show] do
      resources :pages, except: [:show]
    end
    resources :pages, except: [:show], as: :admin_page
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable
  before_save :generate_slug
  has_many :pages

  validates_presence_of :name
  validates_uniqueness_of :name

  alias_attribute :title, :name
end

app/models/concerns/sluggable.rb
module Sluggable
  extend ActiveSupport::Concern

  private
  def generate_slug
    self.slug = title.downcase.gsub(/[^\w|\s]/, '').gsub(/ /, '-')
  end

end

app/models/page.rb
class Page < ActiveRecord::Base
  include Sluggable

  before_save :generate_slug, :rank_self, :rank_siblings

  belongs_to :category
  has_attached_file :image, :styles => { :medium => "350x350>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_presence_of :title
  validates_uniqueness_of :title
  validates_presence_of :content
  validates_presence_of :category

  def self.homepage
    self.where("lower(title) = ?", "home").first
  end

  private

  def rank_self
    unless self.rank
      if Page.any?
        self.rank = Page.order(rank: :desc).first.rank + 1
      else
        self.rank = 1
      end
    end
  end

  def rank_siblings
    siblings = Page.where('rank >= ?', self.rank).order(:rank)
    siblings.each do |s|
      unless s == self
        s.update_attribute(:rank, s.rank + 1)
        s.save
      end
    end
  end

end

app/models/user.rb
EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/

class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :name
  validates_format_of :email, with: EMAIL_REGEX
  validates_uniqueness_of :email

  def self.find_by_email_and_authenticate options={}
    return unless user ||= User.find_by_email(options[:email])
    user.authenticate(options[:password])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :auth_check, :redcarpet

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    current_user != nil
  end

  def auth_check
    head(403) unless logged_in?
  end

  def redcarpet
    @redcarpet ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML.new(filter_html: true, link_attributes: { target: "_blank" } ), autolink: true, tables: true)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :auth_check
  before_action :find_category_or_redirect, except: [:index, :new, :create]
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    Category.create(category_params)
    #flash[:notice] = "Category created!"
    redirect_to categories_path, notice: "Category created!"
  end

  def edit
  end

  def update
    flash_param = @category.update(category_params) ? { flash: { notice: "Category updated" } } : { flash: { error: "Category changes not saved!" } }
    redirect_to action: :index
  end

  def delete
  end

  def destroy
    @category.destroy
    redirect_to action: :index, error: "Category deleted!"
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
  def find_category_or_redirect
    begin
      @category = Category.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      @category = nil
    end
    redirect_to action: :index, flash: { error: "Category not found!" } unless @category
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :find_page_or_redirect, except: [:show, :home, :new, :create]
  before_action :find_category, only: [:new, :create, :update, :edit]
  before_action :populate_markdown, only: [:show, :home]

  def show
  end

  def home
  end

  def edit
  end

  def update
    if @page.update(page_params)
      redirect_to categories_path, notice: "Page updated"
    else
      redirect_to categories_path, flash: { error: "Page not updated!" }
    end
  end
  def new
    @page = Page.new
  end

  def create
    page = Page.new(page_params)
    page.category = @category
    if page.save
      redirect_to categories_path, notice: "Page created!"
    else
      redirect_to categories_path, flash: { error: page.errors.messages }
    end
  end

  private

  def find_category
    @category = Category.find(params[:category_id])
  end

  def find_page_or_redirect
    begin
      @page = Page.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, notice: "Page not found!"
    end
  end

  def populate_markdown
    @page = Page.find_by_slug(params[:slug]) || Page.homepage
    @markdown = redcarpet.render(@page.content).html_safe
  end

  def page_params
    params.require(:page).permit(:title, :content, :category_id, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(email: params[:email], password: params[:password], password_confirmation: params[:password_confirmation])
  end

  def show_login
  end

  def login
    user = User.find_by_email_and_authenticate email: params[:user][:email], password: params[:user][:password]
    if user
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to :root
    else
      flash[:error] = "Login failed"
      render :show_login
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/_category_form.html.haml
= form_for @category do |c|
  = c.label :name
  = c.text_field :name

  = c.submit

app/views/categories/_category_toolbar.html.haml
.btn-toolbar{role: "toolbar"}
  .btn-group.btn-group-sm{role: "group"}
    =link_to new_category_path, {class: "btn btn-default"} do
      %span.fa.fa-plus-square{aria_hidden: "true"}
      New Category

app/views/categories/index.html.haml
%h1 Edit Categories / Pages

=render "category_toolbar"
%br
- @categories.each do |c|
  .well.well-sm
    %h2
      =c.name
    .btn-group.btn-group-xs{role: "group"}
      =link_to new_category_page_path( c ), {class: "btn btn-default"} do
        %span.fa.fa-plus
        New Page
      =link_to edit_category_path( c ), {class: "btn btn-default"} do
        %span.fa.fa-edit
      =link_to category_path( c ), { class: "btn btn-danger", method: :delete, confirm: 'Delete this page?' } do
        %span.fa.fa-trash-o
    %br
    %br
    .list-group
      -c.pages.each do |p|
        .list-group-item
          %h4.list-group-item-heading
            =p.title
            -if p == Page.homepage
              %small
                (This is the home page)
          .btn-group.btn-group-xs{role: "group"}
            =link_to edit_category_page_path( c, p ), {class: "btn btn-default"} do
              %span.fa.fa-edit
            =link_to admin_page_path( p ), { class: "btn btn-danger", method: :delete, confirm: 'Delete this page?' } do
              %span.fa.fa-trash-o

app/views/categories/new.html.haml
%h2 New Category
=render "category_form"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Tree Town School
    =stylesheet_link_tag    'application', media: 'all'
    =javascript_include_tag 'application'
    =csrf_meta_tags
  %body
    .container-fluid
      =render "shared/navbar"
      .row
        .col-md-2
          =render "shared/resources"
        .col-md-7.pull-left.page-content
          -if flash[:notice]
            .alert.alert-success
              =flash[:notice]
          -if flash[:error]
            .alert.alert-danger
              =flash[:error]
          =yield
        .col-md-2.col-md-offset-1
          .sidebar
            %small
              %address
                %strong
                  Tree Town Cooperative Nursery School
                %br
                235 S Kenilworth Avenue
                %br
                Elmhurst, IL 60126
                %br
                %abbr(title="Phone") P:
                (630) 279-8778
                %br
                %abbr(title="Fax") F:
                (630) 279-8781
                %br
                %abbr{title: "Email"} E:
                %a{href: "mailto:treetowncoop@yahoo.com"}treetowncoop@yahoo.com
      =render "shared/footer"
      =debug controller.url_options
      =debug current_user
      =debug flash
      =debug params

app/views/pages/_page_form.html.haml
=form_for [@category, @page], html: { multipart: true } do |p|
  .form-group
    =p.label :title
    =p.text_field :title, class: "form-control"
  .form-group
    =p.label :image
    =p.file_field :image, class: "form-control"
  .form-group
    =p.label :content
    =p.text_area :content, rows: 20, class: "form-control"

  =p.submit class: "btn btn-primary"

app/views/pages/edit.html.haml
%h2 Edit Page
=render "page_form"

app/views/pages/home.html.haml
.jumbotron
  %h1 Welcome to Tree Town!
  %small Nurturing children and families for over 45 years. :)

%article
  =@markdown

app/views/pages/new.html.haml
%h2 New Page
=render "page_form"

app/views/pages/show.html.haml
%h3= @page.title
-unless @page.image.blank?
  .pull-right
    =image_tag @page.image.url(:medium)
=@markdown

app/views/shared/_footer.html.haml
%footer
  .row
    .col-md-2
      &nbsp;
    .col-md-7.text-center
      %small
        Copyright &copy;
        =Date.today.year
        Tree Town Cooperative Nursery School
    .col-md-2.col-md-offset-1
      &nbsp;

app/views/shared/_navbar.html.haml
.row
  %header
    .col-sm-6.text-left
      %span.visible-sm.visible-md.visible-lg
        =image_tag( "treetown_text.png", title: "Tree Town" )
    .col-sm-6.text-right
      =image_tag( "kids_white_115x80.png", title: "Children" )
= nav_bar responsive: true do
  = menu_group do
    - Category.all.order(:id).each do |c|
      - if c.pages.count == 1
        = menu_item c.pages.first.title, c.pages.first == Page.homepage ? root_path : page_path(c.pages.first.slug)
      - else
        = drop_down c.name do
          - c.pages.each do |p|
            = menu_item p.title, page_path(p.slug)
  - if logged_in?
    = menu_group pull: :right do
      = menu_item "Admin", categories_path, pull: :right

app/views/shared/_resources.html.haml
.list_group
  %li Placeholder
  %li For bulletins
  %li And resources
%p
  %small.text-center
    -unless logged_in?
      =link_to "Log in", login_path, {class: "login"}
    -else
      =link_to "Log out", logout_path, {class: "login"}

app/views/users/show_login.html.haml
%h1 Login
=form_tag(controller: :users, action: :login)
=label :user, :email
=text_field :user, :email
%br
=label :user, :password
=password_field :user, :password
%br
=submit_tag "Login"
%br